### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by waitkafuka** [imagemin/imagemin-pngout#4]
I try to use this to compress png files,but got errors.Here is the code:

```
[14:04:01] Starting 'imgmin'...
events.js:183
      throw er; // Unhandled 'error' event
Error: write EPIPE
    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
```

and here is the script:

```
gulp.task('imgmin', function() {
    return gulp.src('qq/*.png')
        .pipe(pngout({
            strategy: 2
        })())
        .pipe(gulp.dest('dist'));
});
```
How can I fix it?

**Comment by sindresorhus** [comment]
You have to attach error listener to the stream to see the actual error.

https://www.google.com/search?q=Error%3A+write+EPIPE+gulp&oq=Error%3A+write+EPIPE+gulp&aqs=chrome..69i57j69i58.951j0j1&sourceid=chrome&ie=UTF-8
